CFLAGS=-Wall
LDFLAGS=-lhidapi
CC=i686-w64-mingw32-gcc
STRIP=i686-w64-mingw32-strip

OBJ=megawin.o


.PHONY:	all

all:	megawin.exe

clean:
	rm -f megawin.exe $(OBJ)

megawin.exe: $(OBJ)
	$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS) && $(STRIP) $@

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<
