CFLAGS=-Wall
LDFLAGS=-lhidapi-libusb

EXE=mg82f6d32
OBJ=megawin.o


.PHONY:	all

all:	$(EXE)

clean:
	rm -f $(EXE) $(OBJ)

$(EXE): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<
